package com.example.langlock;

import android.app.Application;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.os.Build;
import android.util.Log;

import io.realm.Realm;
import io.realm.RealmConfiguration;

import static com.example.langlock.Misc.CHANNEL_ID;
import static com.example.langlock.Misc.DEBUG_TAG;

public class App extends Application {

    private static App instance;

    @Override
    public void onCreate() {
        super.onCreate();
        Log.e(DEBUG_TAG,"App onCreate");

        instance = this;
        configureDatabase();
        DatabaseHelper.getInstance();
        createNotificationChannel();
    }

    private void createNotificationChannel() {
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O){
            NotificationChannel serviceChannel = new NotificationChannel(
                    CHANNEL_ID,
                    "Service channel",
                    NotificationManager.IMPORTANCE_DEFAULT
            );

            NotificationManager manager = getSystemService(NotificationManager.class);
            manager.createNotificationChannel(serviceChannel);
        }
    }

    public static App getInstance(){
        return instance;
    }

    private void configureDatabase(){
        Realm.init(getApplicationContext());
        RealmConfiguration config = new RealmConfiguration.Builder()
                .name(getString(R.string.db))
                .initialData(setData())
                .build();
        Realm.setDefaultConfiguration(config);
    }
    //region words
    private Realm.Transaction setData(){
        return new Realm.Transaction(){
            @Override public void execute(Realm realm){
                realm.insert(new Word(Word.increment(),"четыре сезона", "four seasons"));
                realm.insert(new Word(Word.increment(),"весна", "spring"));
                realm.insert(new Word(Word.increment(),"лето", "summer"));
                realm.insert(new Word(Word.increment(),"осень", "autumn"));
                realm.insert(new Word(Word.increment(),"зима", "winter"));
                realm.insert(new Word(Word.increment(),"животное", "animal"));
                realm.insert(new Word(Word.increment(),"собака", "dog"));
                realm.insert(new Word(Word.increment(),"лягушка", "frog"));
                realm.insert(new Word(Word.increment(),"черепаха", "turtle"));
                realm.insert(new Word(Word.increment(),"горилла", "gorilla"));
                realm.insert(new Word(Word.increment(),"кошка", "cat"));
                realm.insert(new Word(Word.increment(),"медведь", "bear"));
                realm.insert(new Word(Word.increment(),"жираф", "giraffe"));
                realm.insert(new Word(Word.increment(),"курица", "chicken"));
                realm.insert(new Word(Word.increment(),"ящерица", "lizard"));
                realm.insert(new Word(Word.increment(),"свинья", "pig"));
                realm.insert(new Word(Word.increment(),"лошадь", "horse"));
                realm.insert(new Word(Word.increment(),"летучая мышь", "bat"));
                realm.insert(new Word(Word.increment(),"змея", "snake"));
                realm.insert(new Word(Word.increment(),"олень", "deer"));
                realm.insert(new Word(Word.increment(),"лев", "lion"));
                realm.insert(new Word(Word.increment(),"корова", "cow"));
                realm.insert(new Word(Word.increment(),"крокодил", "crocodile"));
                realm.insert(new Word(Word.increment(),"овца", "sheep"));
                realm.insert(new Word(Word.increment(),"зебра", "zebra"));
                realm.insert(new Word(Word.increment(),"лиса", "fox"));
                realm.insert(new Word(Word.increment(),"коза", "goat"));
                realm.insert(new Word(Word.increment(),"обезьяна", "monkey"));
                realm.insert(new Word(Word.increment(),"слон", "elephant"));
                realm.insert(new Word(Word.increment(),"панда", "panda"));
                realm.insert(new Word(Word.increment(),"тигр", "tiger"));
                realm.insert(new Word(Word.increment(),"птица", "bird"));
                realm.insert(new Word(Word.increment(),"чайка", "seagull"));
                realm.insert(new Word(Word.increment(),"павлин", "peacock"));
                realm.insert(new Word(Word.increment(),"ворона", "crow"));
                realm.insert(new Word(Word.increment(),"орел", "eagle"));
                realm.insert(new Word(Word.increment(),"лебедь", "swan"));
                realm.insert(new Word(Word.increment(),"сова", "owl"));
                realm.insert(new Word(Word.increment(),"голубь", "pigeon"));
                realm.insert(new Word(Word.increment(),"попугай", "parrot"));
                realm.insert(new Word(Word.increment(),"утка", "duck"));
                realm.insert(new Word(Word.increment(),"воробей", "sparrow"));
                realm.insert(new Word(Word.increment(),"страус", "ostrich"));
                realm.insert(new Word(Word.increment(),"пингвин", "penguin"));
                realm.insert(new Word(Word.increment(),"насекомое", "insect"));
                realm.insert(new Word(Word.increment(),"муравей", "ant"));
                realm.insert(new Word(Word.increment(),"паук", "spider"));
                realm.insert(new Word(Word.increment(),"пчела", "bee"));
                realm.insert(new Word(Word.increment(),"бабочка", "butterfly"));
                realm.insert(new Word(Word.increment(),"кузнечик", "grasshopper"));
                realm.insert(new Word(Word.increment(),"комар", "mosquito"));
                realm.insert(new Word(Word.increment(),"божья коровка", "ladybug"));
                realm.insert(new Word(Word.increment(),"таракан", "cockroach"));
                realm.insert(new Word(Word.increment(),"куколка", "pupa"));
                realm.insert(new Word(Word.increment(),"богомол", "mantis"));
                realm.insert(new Word(Word.increment(),"стрекоза", "dragonfly"));
                realm.insert(new Word(Word.increment(),"муха", "fly"));
                realm.insert(new Word(Word.increment(),"скарабей", "scarab"));
                realm.insert(new Word(Word.increment(),"рыба", "fish"));
                realm.insert(new Word(Word.increment(),"омар", "lobster"));
                realm.insert(new Word(Word.increment(),"устрица", "oyster"));
                realm.insert(new Word(Word.increment(),"золотая рыбка", "goldfish"));
                realm.insert(new Word(Word.increment(),"дельфин", "dolphin"));
                realm.insert(new Word(Word.increment(),"анчоус", "anchovy"));
                realm.insert(new Word(Word.increment(),"сом", "catfish"));
                realm.insert(new Word(Word.increment(),"осьминог", "octopus"));
                realm.insert(new Word(Word.increment(),"морская звезда", "starfish"));
                realm.insert(new Word(Word.increment(),"коралл", "coral"));
                realm.insert(new Word(Word.increment(),"акула", "shark"));
                realm.insert(new Word(Word.increment(),"лосось", "salmon"));
                realm.insert(new Word(Word.increment(),"тропическая рыба", "tropical fish"));
                realm.insert(new Word(Word.increment(),"кальмар", "squid"));
                realm.insert(new Word(Word.increment(),"угорь", "eel"));
                realm.insert(new Word(Word.increment(),"моллюск", "clam"));
                realm.insert(new Word(Word.increment(),"тунец", "tuna"));
                realm.insert(new Word(Word.increment(),"медуза", "jellyfish"));
                realm.insert(new Word(Word.increment(),"растение", "plant"));
                realm.insert(new Word(Word.increment(),"бамбук", "bamboo"));
                realm.insert(new Word(Word.increment(),"одуванчик", "dandelion"));
                realm.insert(new Word(Word.increment(),"гриб", "mushroom"));
                realm.insert(new Word(Word.increment(),"кактус", "cactus"));
                realm.insert(new Word(Word.increment(),"лотос", "lotus"));
                realm.insert(new Word(Word.increment(),"трава", "grass"));
                realm.insert(new Word(Word.increment(),"роза", "rose"));
                realm.insert(new Word(Word.increment(),"тюльпан", "tulip"));
                realm.insert(new Word(Word.increment(),"подсолнух", "sunflower"));
                realm.insert(new Word(Word.increment(),"лист", "leaf"));
                realm.insert(new Word(Word.increment(),"ветвь", "branch"));
                realm.insert(new Word(Word.increment(),"корень", "root"));
                realm.insert(new Word(Word.increment(),"стебель", "stem"));
                realm.insert(new Word(Word.increment(),"росток", "sprout"));
                realm.insert(new Word(Word.increment(),"цветок", "flower"));
                realm.insert(new Word(Word.increment(),"фрукт", "fruit"));
                realm.insert(new Word(Word.increment(),"еда", "food"));
                realm.insert(new Word(Word.increment(),"напиток", "beverage"));
                realm.insert(new Word(Word.increment(),"завтрак", "breakfast"));
                realm.insert(new Word(Word.increment(),"ужин", "dinner"));
                realm.insert(new Word(Word.increment(),"закуска", "snack"));
                realm.insert(new Word(Word.increment(),"десерт", "dessert"));
                realm.insert(new Word(Word.increment(),"жареная еда", "fried food"));
                realm.insert(new Word(Word.increment(),"жарить", "to roast"));
                realm.insert(new Word(Word.increment(),"варить на пару", "to steam"));
                realm.insert(new Word(Word.increment(),"кипятить", "to boil"));
                realm.insert(new Word(Word.increment(),"добавить специи", "to season"));
                realm.insert(new Word(Word.increment(),"заморозить", "to freeze"));
                realm.insert(new Word(Word.increment(),"ресторан", "restaurant"));
                realm.insert(new Word(Word.increment(),"меню", "menu"));
                realm.insert(new Word(Word.increment(),"мёд", "honey"));
                realm.insert(new Word(Word.increment(),"варенье", "jam"));
                realm.insert(new Word(Word.increment(),"масло", "butter"));
                realm.insert(new Word(Word.increment(),"сливки", "cream"));
                realm.insert(new Word(Word.increment(),"сыр", "cheese"));
                realm.insert(new Word(Word.increment(),"каша", "porridge"));
                realm.insert(new Word(Word.increment(),"оладьи", "pancake"));
                realm.insert(new Word(Word.increment(),"рис", "rice"));
                realm.insert(new Word(Word.increment(),"тост", "toast"));
                realm.insert(new Word(Word.increment(),"жареное яйцо", "fried egg"));
                realm.insert(new Word(Word.increment(),"омлет", "omelet"));
                realm.insert(new Word(Word.increment(),"молоко", "milk"));
                realm.insert(new Word(Word.increment(),"хлеб", "bread"));
                realm.insert(new Word(Word.increment(),"мороженое", "ice cream"));
                realm.insert(new Word(Word.increment(),"пирог", "cake"));
                realm.insert(new Word(Word.increment(),"сладости", "sweets"));
                realm.insert(new Word(Word.increment(),"печенье", "cookie"));
                realm.insert(new Word(Word.increment(),"кекс", "muffin"));
                realm.insert(new Word(Word.increment(),"картофельные чипсы", "potato chips"));
                realm.insert(new Word(Word.increment(),"шоколад", "chocolate"));
                realm.insert(new Word(Word.increment(),"арахисовое масло", "peanut butter"));
                realm.insert(new Word(Word.increment(),"попкорн", "popcorn"));
                realm.insert(new Word(Word.increment(),"леденец", "lollipop"));
                realm.insert(new Word(Word.increment(),"салат", "salad"));
                realm.insert(new Word(Word.increment(),"пицца", "pizza"));
                realm.insert(new Word(Word.increment(),"вафли", "waffle"));
                realm.insert(new Word(Word.increment(),"пончик", "donut"));
                realm.insert(new Word(Word.increment(),"хотдог", "hot dog"));
                realm.insert(new Word(Word.increment(),"гамбургер", "hamburger"));
                realm.insert(new Word(Word.increment(),"картофель-фри", "french fries"));
                realm.insert(new Word(Word.increment(),"макаронные изделия", "pasta"));
                realm.insert(new Word(Word.increment(),"закуска", "appetizer"));
                realm.insert(new Word(Word.increment(),"суп", "soup"));
                realm.insert(new Word(Word.increment(),"суши", "sushi"));
                realm.insert(new Word(Word.increment(),"оливковое масло", "olive oil"));
                realm.insert(new Word(Word.increment(),"круассан", "croissant"));
                realm.insert(new Word(Word.increment(),"стейк", "steak"));
                realm.insert(new Word(Word.increment(),"бутерброд", "sandwich"));
                realm.insert(new Word(Word.increment(),"ветчина", "ham"));
                realm.insert(new Word(Word.increment(),"сосиска", "sausage"));
                realm.insert(new Word(Word.increment(),"котлета", "cutlet"));
                realm.insert(new Word(Word.increment(),"шашлык", "skewer"));
                realm.insert(new Word(Word.increment(),"хлопья", "cereals"));
                realm.insert(new Word(Word.increment(),"консервы", "canned food"));
                realm.insert(new Word(Word.increment(),"майонез", "mayonnaise"));
                realm.insert(new Word(Word.increment(),"уксус", "vinegar"));
                realm.insert(new Word(Word.increment(),"сахар", "sugar"));
                realm.insert(new Word(Word.increment(),"поваренная соль", "salt"));
                realm.insert(new Word(Word.increment(),"перец", "pepper"));
                realm.insert(new Word(Word.increment(),"порошок красного перца", "red pepper powder"));
                realm.insert(new Word(Word.increment(),"фруктовый сок", "fruit juice"));
                realm.insert(new Word(Word.increment(),"вода", "water"));
                realm.insert(new Word(Word.increment(),"вода со льдом", "ice water"));
                realm.insert(new Word(Word.increment(),"горячая вода", "hot water"));
                realm.insert(new Word(Word.increment(),"кола", "Coke"));
                realm.insert(new Word(Word.increment(),"спрайт", "Sprite"));
                realm.insert(new Word(Word.increment(),"чай со льдом", "iced tea"));
                realm.insert(new Word(Word.increment(),"лимонад", "lemonade"));
                realm.insert(new Word(Word.increment(),"горячий шоколад", "hot chocolate"));
                realm.insert(new Word(Word.increment(),"кофе", "coffee"));
                realm.insert(new Word(Word.increment(),"американо", "americano"));
                realm.insert(new Word(Word.increment(),"эcпрессо", "espresso"));
                realm.insert(new Word(Word.increment(),"чай", "tea"));
                realm.insert(new Word(Word.increment(),"зеленый чай", "green tea"));
                realm.insert(new Word(Word.increment(),"черный чай", "black tea"));
                realm.insert(new Word(Word.increment(),"вино", "wine"));
                realm.insert(new Word(Word.increment(),"шампанское", "champagne"));
                realm.insert(new Word(Word.increment(),"пиво", "beer"));
                realm.insert(new Word(Word.increment(),"виски", "whisky"));
                realm.insert(new Word(Word.increment(),"водка", "vodka"));
                realm.insert(new Word(Word.increment(),"мясо", "meat"));
                realm.insert(new Word(Word.increment(),"фрукт", "fruit"));
                realm.insert(new Word(Word.increment(),"овощи", "vegetable"));
                realm.insert(new Word(Word.increment(),"яйцо", "egg"));
                realm.insert(new Word(Word.increment(),"курица", "chicken"));
                realm.insert(new Word(Word.increment(),"свинина", "pork"));
                realm.insert(new Word(Word.increment(),"говядина", "beef"));
                realm.insert(new Word(Word.increment(),"бекон", "bacon"));
                realm.insert(new Word(Word.increment(),"сосиска", "sausage"));
                realm.insert(new Word(Word.increment(),"ветчина", "ham"));
                realm.insert(new Word(Word.increment(),"рыба", "fish"));
                realm.insert(new Word(Word.increment(),"яблоко", "apple"));
                realm.insert(new Word(Word.increment(),"виноград", "grapes"));
                realm.insert(new Word(Word.increment(),"арбуз", "watermelon"));
                realm.insert(new Word(Word.increment(),"клубника", "strawberry"));
                realm.insert(new Word(Word.increment(),"дыня", "melon"));
                realm.insert(new Word(Word.increment(),"манго", "mango"));
                realm.insert(new Word(Word.increment(),"персик", "peach"));
                realm.insert(new Word(Word.increment(),"киви", "kiwi"));
                realm.insert(new Word(Word.increment(),"банан", "banana"));
                realm.insert(new Word(Word.increment(),"апельсин", "orange"));
                realm.insert(new Word(Word.increment(),"кокос", "coconut"));
                realm.insert(new Word(Word.increment(),"папайя", "papaya"));
                realm.insert(new Word(Word.increment(),"груша", "pear"));
                realm.insert(new Word(Word.increment(),"мандарин", "tangerine"));
                realm.insert(new Word(Word.increment(),"ананас", "pineapple"));
                realm.insert(new Word(Word.increment(),"черника", "blueberries"));
                realm.insert(new Word(Word.increment(),"лимон", "lemon"));
                realm.insert(new Word(Word.increment(),"картошка", "potato"));
                realm.insert(new Word(Word.increment(),"сладкая картошка", "sweet potato"));
                realm.insert(new Word(Word.increment(),"баклажан", "eggplant"));
                realm.insert(new Word(Word.increment(),"чеснок", "garlic"));
                realm.insert(new Word(Word.increment(),"редька", "radish"));
                realm.insert(new Word(Word.increment(),"китайская капуста", "chinese cabbage"));
                realm.insert(new Word(Word.increment(),"гриб", "mushroom"));
                realm.insert(new Word(Word.increment(),"лук-порей", "chives"));
                realm.insert(new Word(Word.increment(),"шпинат", "spinach"));
                realm.insert(new Word(Word.increment(),"капуста", "cabbage"));
                realm.insert(new Word(Word.increment(),"лук", "onion"));
                realm.insert(new Word(Word.increment(),"кукуруза", "corn"));
                realm.insert(new Word(Word.increment(),"ростки бобов", "bean sprouts"));
                realm.insert(new Word(Word.increment(),"помидор", "tomato"));
                realm.insert(new Word(Word.increment(),"зеленый лук", "green onion"));
                realm.insert(new Word(Word.increment(),"тыква", "pumpkin"));
                realm.insert(new Word(Word.increment(),"морковь", "carrot"));
                realm.insert(new Word(Word.increment(),"перец чили", "chilli pepper"));
                realm.insert(new Word(Word.increment(),"молоко", "milk"));
                realm.insert(new Word(Word.increment(),"сыр", "cheese"));
                realm.insert(new Word(Word.increment(),"йогурт", "yogurt"));
                realm.insert(new Word(Word.increment(),"грецкий орех", "walnut"));
                realm.insert(new Word(Word.increment(),"миндаль", "almond"));
                realm.insert(new Word(Word.increment(),"арахис", "peanut"));
                realm.insert(new Word(Word.increment(),"оливки", "olive"));
                realm.insert(new Word(Word.increment(),"рис", "rice"));
                realm.insert(new Word(Word.increment(),"водоросли", "seaweed"));
                realm.insert(new Word(Word.increment(),"семья", "family"));
                realm.insert(new Word(Word.increment(),"отец", "father"));
                realm.insert(new Word(Word.increment(),"мама", "mother"));
                realm.insert(new Word(Word.increment(),"сын", "son"));
                realm.insert(new Word(Word.increment(),"родители", "parents"));
                realm.insert(new Word(Word.increment(),"дети", "children"));
                realm.insert(new Word(Word.increment(),"муж", "husband"));
                realm.insert(new Word(Word.increment(),"братья", "brothers"));
                realm.insert(new Word(Word.increment(),"сестры", "sisters"));
                realm.insert(new Word(Word.increment(),"брат и сестра", "brother and sister"));
                realm.insert(new Word(Word.increment(),"младший брат", "younger brother"));
                realm.insert(new Word(Word.increment(),"старшая сестра", "older sister"));
                realm.insert(new Word(Word.increment(),"сводная сестра", "stepsister"));
                realm.insert(new Word(Word.increment(),"старший брат", "older brother"));
                realm.insert(new Word(Word.increment(),"сводный брат", "stepbrother"));
                realm.insert(new Word(Word.increment(),"младшая сестра", "younger sister"));
                realm.insert(new Word(Word.increment(),"родственники", "relatives"));
                realm.insert(new Word(Word.increment(),"бабушка", "grandmother"));
                realm.insert(new Word(Word.increment(),"дед", "grandfather"));
                realm.insert(new Word(Word.increment(),"внук", "grandson"));
                realm.insert(new Word(Word.increment(),"внучка", "granddaughter"));
                realm.insert(new Word(Word.increment(),"внук", "grandchild"));
                realm.insert(new Word(Word.increment(),"дядя", "uncle"));
                realm.insert(new Word(Word.increment(),"двоюродная сестра", "cousin"));
                realm.insert(new Word(Word.increment(),"брак", "marriage"));
                realm.insert(new Word(Word.increment(),"развод", "divorce"));
                realm.insert(new Word(Word.increment(),"вторая половинка", "lover"));
                realm.insert(new Word(Word.increment(),"парень", "boyfriend"));
                realm.insert(new Word(Word.increment(),"девушка", "girlfriend"));
                realm.insert(new Word(Word.increment(),"флиртовать", "to flirt"));
                realm.insert(new Word(Word.increment(),"первая любовь", "first love"));
                realm.insert(new Word(Word.increment(),"неразделенная любовь", "unrequited love"));
                realm.insert(new Word(Word.increment(),"отношения", "relationship"));
                realm.insert(new Word(Word.increment(),"свидание", "date"));
                realm.insert(new Word(Word.increment(),"признание", "confession"));
                realm.insert(new Word(Word.increment(),"держаться за руки", "to hold hands"));
                realm.insert(new Word(Word.increment(),"объятие", "hug"));
                realm.insert(new Word(Word.increment(),"чмокнуть", "peck"));
                realm.insert(new Word(Word.increment(),"французский поцелуй", "kiss"));
                realm.insert(new Word(Word.increment(),"расставание", "break up"));
                realm.insert(new Word(Word.increment(),"встречаться", "to date"));
                realm.insert(new Word(Word.increment(),"свидание в слепую", "blind date"));
                realm.insert(new Word(Word.increment(),"друг", "friend"));
                realm.insert(new Word(Word.increment(),"дружба", "friendship"));
                realm.insert(new Word(Word.increment(),"любовные отношения", "love"));
                realm.insert(new Word(Word.increment(),"предложение", "proposal"));
                realm.insert(new Word(Word.increment(),"помолвка", "engagement"));
                realm.insert(new Word(Word.increment(),"враг", "enemy"));
                realm.insert(new Word(Word.increment(),"коллега", "colleague"));
                realm.insert(new Word(Word.increment(),"сосед", "neighbor"));
                realm.insert(new Word(Word.increment(),"предательство", "betrayal"));
                realm.insert(new Word(Word.increment(),"ученик", "student"));
                realm.insert(new Word(Word.increment(),"начальник", "boss"));
                realm.insert(new Word(Word.increment(),"встать", "to wake up"));
                realm.insert(new Word(Word.increment(),"умываться", "to wash face"));
                realm.insert(new Word(Word.increment(),"бриться", "to shave"));
                realm.insert(new Word(Word.increment(),"чистить зубы", "to brush teeth"));
                realm.insert(new Word(Word.increment(),"мыть руки", "to wash hands"));
                realm.insert(new Word(Word.increment(),"принимать ванну", "to take a bath"));
                realm.insert(new Word(Word.increment(),"принимать душ", "to take a shower"));
                realm.insert(new Word(Word.increment(),"спать", "to sleep"));
                realm.insert(new Word(Word.increment(),"снять одежду", "to take off clothes"));
                realm.insert(new Word(Word.increment(),"надеть туфли", "to put on shoes"));
                realm.insert(new Word(Word.increment(),"мыть голову", "to wash hair"));
                realm.insert(new Word(Word.increment(),"убирать", "to clean up"));
                realm.insert(new Word(Word.increment(),"готовить", "to cook"));
                realm.insert(new Word(Word.increment(),"кушать", "to eat"));
                realm.insert(new Word(Word.increment(),"завтракать", "to have breakfast"));
                realm.insert(new Word(Word.increment(),"ужинать", "to have dinner"));
                realm.insert(new Word(Word.increment(),"мыть посуду", "to do the dishes"));
                realm.insert(new Word(Word.increment(),"стирать", "to do the laundry"));
                realm.insert(new Word(Word.increment(),"заботиться о ребенке", "to take care of a child"));
                realm.insert(new Word(Word.increment(),"приветствовать", "to greet"));
                realm.insert(new Word(Word.increment(),"заказывать", "to order"));
                realm.insert(new Word(Word.increment(),"заказать еду", "to order food"));
                realm.insert(new Word(Word.increment(),"купить вещи", "to buy things"));
                realm.insert(new Word(Word.increment(),"отправляться за покупками", "to shop"));
                realm.insert(new Word(Word.increment(),"пить воду", "to drink water"));
                realm.insert(new Word(Word.increment(),"курить", "to smoke"));
                realm.insert(new Word(Word.increment(),"пить алкоголь", "to drink alcohol"));
                realm.insert(new Word(Word.increment(),"заниматься спортом", "to work out"));
                realm.insert(new Word(Word.increment(),"ходить", "to walk"));
                realm.insert(new Word(Word.increment(),"бегать трусцой", "to go jogging"));
                realm.insert(new Word(Word.increment(),"кататься на велосипеде", "to ride a bike"));
                realm.insert(new Word(Word.increment(),"ехать на метро", "to take the subway"));
                realm.insert(new Word(Word.increment(),"ехать на автобусе", "to take the bus"));
                realm.insert(new Word(Word.increment(),"ехать на такси", "to take the taxi"));
                realm.insert(new Word(Word.increment(),"лететь", "to fly"));
                realm.insert(new Word(Word.increment(),"путешествовать", "to travel"));
                realm.insert(new Word(Word.increment(),"водить машину", "to drive"));
                realm.insert(new Word(Word.increment(),"припарковаться", "to park"));
                realm.insert(new Word(Word.increment(),"звонить", "to make a call"));
                realm.insert(new Word(Word.increment(),"учиться", "to study"));
                realm.insert(new Word(Word.increment(),"делать домашнюю работу", "to do homework"));
                realm.insert(new Word(Word.increment(),"прогуляться", "to take a walk"));
                realm.insert(new Word(Word.increment(),"идти в школу", "to go to school"));
                realm.insert(new Word(Word.increment(),"прийти домой из школы", "to come home from school"));
                realm.insert(new Word(Word.increment(),"пить кофе", "to drink coffee"));
                realm.insert(new Word(Word.increment(),"болтать", "to chat"));
                realm.insert(new Word(Word.increment(),"вздремнуть", "to take a nap"));
                realm.insert(new Word(Word.increment(),"слушать музыку", "to listen to music"));
                realm.insert(new Word(Word.increment(),"играть в игры", "to play games"));
                realm.insert(new Word(Word.increment(),"смотреть телевизор", "to watch TV"));
                realm.insert(new Word(Word.increment(),"смотреть фильм", "to watch a movie"));
                realm.insert(new Word(Word.increment(),"читать", "to read"));
                realm.insert(new Word(Word.increment(),"петь", "to sing"));
                realm.insert(new Word(Word.increment(),"гостиная", "living room"));
                realm.insert(new Word(Word.increment(),"кухня", "kitchen"));
                realm.insert(new Word(Word.increment(),"спальня", "bedroom"));
                realm.insert(new Word(Word.increment(),"ванная", "bathroom"));
                realm.insert(new Word(Word.increment(),"двор", "yard"));
                realm.insert(new Word(Word.increment(),"сад", "garden"));
                realm.insert(new Word(Word.increment(),"пол", "floor"));
                realm.insert(new Word(Word.increment(),"крыша", "roof"));
                realm.insert(new Word(Word.increment(),"лестница", "stairs"));
                realm.insert(new Word(Word.increment(),"окно", "window"));
                realm.insert(new Word(Word.increment(),"этажом ниже", "downstairs"));
                realm.insert(new Word(Word.increment(),"этажом выше", "upstairs"));
                realm.insert(new Word(Word.increment(),"почтовый ящик", "mailbox"));
                realm.insert(new Word(Word.increment(),"холодильник", "refrigerator"));
                realm.insert(new Word(Word.increment(),"чайник", "kettle"));
                realm.insert(new Word(Word.increment(),"сковорода", "frying pan"));
                realm.insert(new Word(Word.increment(),"ковшик", "ladle"));
                realm.insert(new Word(Word.increment(),"ложка", "spoon"));
                realm.insert(new Word(Word.increment(),"палочки для еды", "chopsticks"));
                realm.insert(new Word(Word.increment(),"вилка", "fork"));
                realm.insert(new Word(Word.increment(),"нож", "knife"));
                realm.insert(new Word(Word.increment(),"чайная ложка", "teaspoon"));
                realm.insert(new Word(Word.increment(),"бумажный стакан", "paper cup"));
                realm.insert(new Word(Word.increment(),"стакан", "glass"));
                realm.insert(new Word(Word.increment(),"бутылка с водой", "water bottle"));
                realm.insert(new Word(Word.increment(),"тарелка", "plate"));
                realm.insert(new Word(Word.increment(),"миска", "bowl"));
                realm.insert(new Word(Word.increment(),"стол", "table"));
                realm.insert(new Word(Word.increment(),"газовая плита", "gas stove"));
                realm.insert(new Word(Word.increment(),"пылесос", "vacuum cleaner"));
                realm.insert(new Word(Word.increment(),"мусор", "trash"));
                realm.insert(new Word(Word.increment(),"стиральная машина", "washer"));
                realm.insert(new Word(Word.increment(),"прачечная", "laundry"));
                realm.insert(new Word(Word.increment(),"шампунь", "shampoo"));
                realm.insert(new Word(Word.increment(),"кондиционер", "conditioner"));
                realm.insert(new Word(Word.increment(),"гель для тела", "body wash"));
                realm.insert(new Word(Word.increment(),"сушилка", "dryer"));
                realm.insert(new Word(Word.increment(),"полотенце", "towel"));
                realm.insert(new Word(Word.increment(),"носовой платок", "handkerchief"));
                realm.insert(new Word(Word.increment(),"туалетная бумага", "toilet paper"));
                realm.insert(new Word(Word.increment(),"салфетки", "tissue"));
                realm.insert(new Word(Word.increment(),"расческа", "comb"));
                realm.insert(new Word(Word.increment(),"туалет", "toilet"));
                realm.insert(new Word(Word.increment(),"зубная щетка", "toothbrush"));
                realm.insert(new Word(Word.increment(),"зубная паста", "toothpaste"));
                realm.insert(new Word(Word.increment(),"бритва", "razor"));
                realm.insert(new Word(Word.increment(),"мусорное ведро", "trash can"));
                realm.insert(new Word(Word.increment(),"зонтик", "umbrella"));
                realm.insert(new Word(Word.increment(),"диван", "sofa"));
                realm.insert(new Word(Word.increment(),"стул", "chair"));
                realm.insert(new Word(Word.increment(),"стол", "table"));
                realm.insert(new Word(Word.increment(),"книжный шкаф", "bookcase"));
                realm.insert(new Word(Word.increment(),"часы наручные", "watch"));
                realm.insert(new Word(Word.increment(),"часы", "clock"));
                realm.insert(new Word(Word.increment(),"игрушка", "toy"));
                realm.insert(new Word(Word.increment(),"выдвижной ящик", "drawer"));
                realm.insert(new Word(Word.increment(),"пианино", "piano"));
                realm.insert(new Word(Word.increment(),"зеркало", "mirror"));
                realm.insert(new Word(Word.increment(),"занавес", "curtain"));
                realm.insert(new Word(Word.increment(),"свет", "light"));
                realm.insert(new Word(Word.increment(),"стенной шкаф", "closet"));
                realm.insert(new Word(Word.increment(),"вешалка", "hanger"));
                realm.insert(new Word(Word.increment(),"радио", "radio"));
                realm.insert(new Word(Word.increment(),"телефон", "phone"));
                realm.insert(new Word(Word.increment(),"фоторамка", "photo frame"));
                realm.insert(new Word(Word.increment(),"постель", "bed"));
                realm.insert(new Word(Word.increment(),"диванная подушка", "cushion"));
                realm.insert(new Word(Word.increment(),"одеяло", "blanket"));
                realm.insert(new Word(Word.increment(),"подушка", "pillow"));
                realm.insert(new Word(Word.increment(),"компьютер", "computer"));
                realm.insert(new Word(Word.increment(),"ноутбук", "laptop"));
                realm.insert(new Word(Word.increment(),"сканер", "scanner"));
                realm.insert(new Word(Word.increment(),"принтер", "printer"));
                realm.insert(new Word(Word.increment(),"камера", "camera"));
                realm.insert(new Word(Word.increment(),"кондиционер", "air conditioner"));
                realm.insert(new Word(Word.increment(),"вентилятор", "electric fan"));
                realm.insert(new Word(Word.increment(),"лампочка", "electric bulb"));
                realm.insert(new Word(Word.increment(),"ключи", "key"));
                realm.insert(new Word(Word.increment(),"виды спорта", "sports"));
                realm.insert(new Word(Word.increment(),"гольф", "golf"));
                realm.insert(new Word(Word.increment(),"баскетбол", "basketball"));
                realm.insert(new Word(Word.increment(),"бильярд", "billiards"));
                realm.insert(new Word(Word.increment(),"борьба", "wrestling"));
                realm.insert(new Word(Word.increment(),"марафон", "marathon"));
                realm.insert(new Word(Word.increment(),"волейбол", "volleyball"));
                realm.insert(new Word(Word.increment(),"бадминтон", "badminton"));
                realm.insert(new Word(Word.increment(),"бокс", "boxing"));
                realm.insert(new Word(Word.increment(),"боулинг", "bowling"));
                realm.insert(new Word(Word.increment(),"серфинг", "surfing"));
                realm.insert(new Word(Word.increment(),"плавание", "swimming"));
                realm.insert(new Word(Word.increment(),"подводное плавание", "scuba diving"));
                realm.insert(new Word(Word.increment(),"лыжи", "ski"));
                realm.insert(new Word(Word.increment(),"бейсбол", "baseball"));
                realm.insert(new Word(Word.increment(),"йога", "yoga"));
                realm.insert(new Word(Word.increment(),"легкая атлетика", "track"));
                realm.insert(new Word(Word.increment(),"бег", "jogging"));
                realm.insert(new Word(Word.increment(),"гимнастика", "gymnastics"));
                realm.insert(new Word(Word.increment(),"футбол", "soccer"));
                realm.insert(new Word(Word.increment(),"настольный теннис", "ping-pong"));
                realm.insert(new Word(Word.increment(),"тэквондо", "taekwondo"));
                realm.insert(new Word(Word.increment(),"теннис", "tennis"));
                realm.insert(new Word(Word.increment(),"мяч", "ball"));
                realm.insert(new Word(Word.increment(),"тренировка", "workout"));
                realm.insert(new Word(Word.increment(),"игровая площадка", "playing field"));
                realm.insert(new Word(Word.increment(),"тренер", "coach"));
                realm.insert(new Word(Word.increment(),"менеджер", "manager"));
                realm.insert(new Word(Word.increment(),"предупреждение", "warning"));
                realm.insert(new Word(Word.increment(),"устранение", "dismissal"));
                realm.insert(new Word(Word.increment(),"выигрывать", "to win"));
                realm.insert(new Word(Word.increment(),"проигрывать", "to lose"));
                realm.insert(new Word(Word.increment(),"победитель", "winner"));
                realm.insert(new Word(Word.increment(),"проигравший", "loser"));
                realm.insert(new Word(Word.increment(),"счет", "score"));
                realm.insert(new Word(Word.increment(),"зритель", "spectator"));
                realm.insert(new Word(Word.increment(),"фотографирование", "taking a picture"));
                realm.insert(new Word(Word.increment(),"рисование", "drawing"));
                realm.insert(new Word(Word.increment(),"играть на музыкальных инструментах", "playing musical instruments"));
                realm.insert(new Word(Word.increment(),"чтение", "reading"));
                realm.insert(new Word(Word.increment(),"готовка", "cooking"));
                realm.insert(new Word(Word.increment(),"вождение машины", "drive"));
                realm.insert(new Word(Word.increment(),"упражнение", "exercise"));
                realm.insert(new Word(Word.increment(),"рыбалка", "fishing"));
                realm.insert(new Word(Word.increment(),"скалолазание", "mountain climbing"));
                realm.insert(new Word(Word.increment(),"шахматы", "chess"));
                realm.insert(new Word(Word.increment(),"игральные карты", "playing cards"));
                realm.insert(new Word(Word.increment(),"видео игра", "video game"));
                realm.insert(new Word(Word.increment(),"онлайн игра", "online game"));
                realm.insert(new Word(Word.increment(),"смотреть фильмы", "watching a movie"));
                realm.insert(new Word(Word.increment(),"питье", "drinking"));
                realm.insert(new Word(Word.increment(),"маникюр", "nail art"));
                realm.insert(new Word(Word.increment(),"путешествие", "travel"));
                realm.insert(new Word(Word.increment(),"писание", "writing"));
                realm.insert(new Word(Word.increment(),"поход", "camping"));
                realm.insert(new Word(Word.increment(),"поход по магазинам", "shopping"));
                realm.insert(new Word(Word.increment(),"татуировка", "tattoo"));
                realm.insert(new Word(Word.increment(),"коллекция", "collection"));
                realm.insert(new Word(Word.increment(),"болтать", "chattering"));
                realm.insert(new Word(Word.increment(),"спать", "sleeping"));
                realm.insert(new Word(Word.increment(),"путешествие", "trip"));
                realm.insert(new Word(Word.increment(),"жилье", "accommodation"));
                realm.insert(new Word(Word.increment(),"гостиница", "hotel"));
                realm.insert(new Word(Word.increment(),"медовый месяц", "honeymoon"));
                realm.insert(new Word(Word.increment(),"путешествие с рюкзаком", "backpacking"));
                realm.insert(new Word(Word.increment(),"сувенир", "souvenir"));
                realm.insert(new Word(Word.increment(),"дюти фри", "duty-free shop"));
                realm.insert(new Word(Word.increment(),"справочный стол", "information desk"));
                realm.insert(new Word(Word.increment(),"туристическое агенство", "Travel agency"));
                realm.insert(new Word(Word.increment(),"отпуск", "vacation"));
                realm.insert(new Word(Word.increment(),"осмотр достопримечательностей", "sightseeing"));
                realm.insert(new Word(Word.increment(),"карта", "map"));
                realm.insert(new Word(Word.increment(),"аэропорт", "airport"));
                realm.insert(new Word(Word.increment(),"заграничный пасспорт", "passport"));
                realm.insert(new Word(Word.increment(),"чемодан", "suitcase"));
                realm.insert(new Word(Word.increment(),"авиабилет", "airline ticket"));
                realm.insert(new Word(Word.increment(),"обмен денег", "money exchange"));
                realm.insert(new Word(Word.increment(),"обменный курс", "exchange rate"));
                realm.insert(new Word(Word.increment(),"бортпроводник", "flight attendant"));
                realm.insert(new Word(Word.increment(),"экстренный выход", "emergency exit"));
                realm.insert(new Word(Word.increment(),"разница во времени", "time difference"));
                realm.insert(new Word(Word.increment(),"автобус в аэропорту", "airport bus"));
                realm.insert(new Word(Word.increment(),"встреча в аэропорту", "Pick-up service"));
                realm.insert(new Word(Word.increment(),"регистрироваться", "check-in"));
                realm.insert(new Word(Word.increment(),"выезд", "check-out"));
                realm.insert(new Word(Word.increment(),"резервирование", "reservation"));
                realm.insert(new Word(Word.increment(),"стойка регистрации", "front desk"));
                realm.insert(new Word(Word.increment(),"лобби", "lobby"));
                realm.insert(new Word(Word.increment(),"бесплатный", "free"));
                realm.insert(new Word(Word.increment(),"чаевые", "tip"));
                realm.insert(new Word(Word.increment(),"сейф", "safe"));
                realm.insert(new Word(Word.increment(),"транспорт", "transportation"));
                realm.insert(new Word(Word.increment(),"такси", "taxi"));
                realm.insert(new Word(Word.increment(),"палатка", "tent"));
                realm.insert(new Word(Word.increment(),"поход по магазинам", "shopping"));
                realm.insert(new Word(Word.increment(),"торговый дом", "shopping mall"));
                realm.insert(new Word(Word.increment(),"галерея искусств", "art gallery"));
                realm.insert(new Word(Word.increment(),"купальник", "swimsuit"));
                realm.insert(new Word(Word.increment(),"бикини", "bikini"));
                realm.insert(new Word(Word.increment(),"камера", "camera"));
                realm.insert(new Word(Word.increment(),"селфи палка", "selfie stick"));
                realm.insert(new Word(Word.increment(),"солнечные очки", "sunglasses"));
                realm.insert(new Word(Word.increment(),"роуминг", "data roaming"));
                realm.insert(new Word(Word.increment(),"одежда", "clothes"));
                realm.insert(new Word(Word.increment(),"верхняя одежда", "tops"));
                realm.insert(new Word(Word.increment(),"рукав", "sleeve"));
                realm.insert(new Word(Word.increment(),"куртка", "coat"));
                realm.insert(new Word(Word.increment(),"нижнее белье", "underwear"));
                realm.insert(new Word(Word.increment(),"футболка", "t-shirt"));
                realm.insert(new Word(Word.increment(),"блузка", "blouse"));
                realm.insert(new Word(Word.increment(),"рубашка", "shirt"));
                realm.insert(new Word(Word.increment(),"v-образный вырез", "v-neck"));
                realm.insert(new Word(Word.increment(),"брюки", "pants"));
                realm.insert(new Word(Word.increment(),"юбка", "skirt"));
                realm.insert(new Word(Word.increment(),"рубашка с короткими рукавами", "short-sleeve shirt"));
                realm.insert(new Word(Word.increment(),"шорты", "shorts"));
                realm.insert(new Word(Word.increment(),"джинсы", "jeans"));
                realm.insert(new Word(Word.increment(),"узкие джинсы", "skinny jeans"));
                realm.insert(new Word(Word.increment(),"галстук", "tie"));
                realm.insert(new Word(Word.increment(),"платье", "dress"));
                realm.insert(new Word(Word.increment(),"куртка", "coat"));
                realm.insert(new Word(Word.increment(),"вязаные изделия", "knits"));
                realm.insert(new Word(Word.increment(),"куртка", "jacket"));
                realm.insert(new Word(Word.increment(),"майка", "tank top  "));
                realm.insert(new Word(Word.increment(),"пижама", "pajamas"));
                realm.insert(new Word(Word.increment(),"пояс", "belt"));
                realm.insert(new Word(Word.increment(),"шапка", "hat"));
                realm.insert(new Word(Word.increment(),"перчатки", "gloves"));
                realm.insert(new Word(Word.increment(),"шарф", "scarf"));
                realm.insert(new Word(Word.increment(),"солнечные очки", "sunglasses"));
                realm.insert(new Word(Word.increment(),"носки", "socks"));
                realm.insert(new Word(Word.increment(),"купальные костюмы", "swimsuit"));
                realm.insert(new Word(Word.increment(),"бикини", "bikini"));
                realm.insert(new Word(Word.increment(),"бюстгальтер", "bra"));
                realm.insert(new Word(Word.increment(),"трусы", "underwear"));
                realm.insert(new Word(Word.increment(),"колготки", "tights"));
                realm.insert(new Word(Word.increment(),"обувь для тенниса", "tennis shoes"));
                realm.insert(new Word(Word.increment(),"обувь", "shoes"));
                realm.insert(new Word(Word.increment(),"туфли на высоком каблуке", "high heels"));
                realm.insert(new Word(Word.increment(),"домашние тапочки", "slippers"));
                realm.insert(new Word(Word.increment(),"молния", "zipper"));
                realm.insert(new Word(Word.increment(),"пуговица", "button"));
                realm.insert(new Word(Word.increment(),"ожерелье", "necklace"));
                realm.insert(new Word(Word.increment(),"серьги", "earrings"));
                realm.insert(new Word(Word.increment(),"очки", "glasses"));
                realm.insert(new Word(Word.increment(),"браслет", "bracelet"));
                realm.insert(new Word(Word.increment(),"кольца", "rings"));
                realm.insert(new Word(Word.increment(),"белый", "white"));
                realm.insert(new Word(Word.increment(),"желтый", "yellow"));
                realm.insert(new Word(Word.increment(),"оранжевый", "orange"));
                realm.insert(new Word(Word.increment(),"розовый", "pink"));
                realm.insert(new Word(Word.increment(),"красный", "red"));
                realm.insert(new Word(Word.increment(),"коричневый", "brown"));
                realm.insert(new Word(Word.increment(),"светло-зеленый", "light green"));
                realm.insert(new Word(Word.increment(),"зеленый", "green"));
                realm.insert(new Word(Word.increment(),"голубой", "skyblue"));
                realm.insert(new Word(Word.increment(),"синий", "blue"));
                realm.insert(new Word(Word.increment(),"темно-синий", "navy"));
                realm.insert(new Word(Word.increment(),"пурпурный", "purple"));
                realm.insert(new Word(Word.increment(),"черный", "black"));
                realm.insert(new Word(Word.increment(),"серебряный", "silver"));
                realm.insert(new Word(Word.increment(),"золотой", "gold"));
                realm.insert(new Word(Word.increment(),"здание", "building"));
                realm.insert(new Word(Word.increment(),"театр", "theater"));
                realm.insert(new Word(Word.increment(),"ресторан", "restaurant"));
                realm.insert(new Word(Word.increment(),"бассейн", "swimming pool"));
                realm.insert(new Word(Word.increment(),"пекарня", "bakery"));
                realm.insert(new Word(Word.increment(),"кафе", "cafe"));
                realm.insert(new Word(Word.increment(),"магазин", "store"));
                realm.insert(new Word(Word.increment(),"супермаркет", "supermarket"));
                realm.insert(new Word(Word.increment(),"торговый центр", "department store"));
                realm.insert(new Word(Word.increment(),"торговый дом", "shopping mall"));
                realm.insert(new Word(Word.increment(),"парк развлечений", "amusement park"));
                realm.insert(new Word(Word.increment(),"зоопарк", "zoo"));
                realm.insert(new Word(Word.increment(),"туалет", "restroom"));
                realm.insert(new Word(Word.increment(),"игровая площадка", "playing field"));
                realm.insert(new Word(Word.increment(),"телевизионная станция", "broadcast station"));
                realm.insert(new Word(Word.increment(),"киоск", "convenience store"));
                realm.insert(new Word(Word.increment(),"почта", "post office"));
                realm.insert(new Word(Word.increment(),"полицейское управление", "police office"));
                realm.insert(new Word(Word.increment(),"суд", "court"));
                realm.insert(new Word(Word.increment(),"отделение скорой помощи", "emergency room"));
                realm.insert(new Word(Word.increment(),"больница", "hospital"));
                realm.insert(new Word(Word.increment(),"прачечная", "laundromat"));
                realm.insert(new Word(Word.increment(),"аптека", "pharmacy"));
                realm.insert(new Word(Word.increment(),"бар", "bar"));
                realm.insert(new Word(Word.increment(),"парк", "park"));
                realm.insert(new Word(Word.increment(),"автобусная остановка", "bus stop"));
                realm.insert(new Word(Word.increment(),"станция метро", "subway station"));
                realm.insert(new Word(Word.increment(),"железнодорожная станция", "train station"));
                realm.insert(new Word(Word.increment(),"аэропорт", "airport"));
                realm.insert(new Word(Word.increment(),"музей", "museum"));
                realm.insert(new Word(Word.increment(),"галерея искусств", "art gallery"));
                realm.insert(new Word(Word.increment(),"квартира", "apartment"));
                realm.insert(new Word(Word.increment(),"гостиница", "hotel"));
                realm.insert(new Word(Word.increment(),"академия", "academy"));
                realm.insert(new Word(Word.increment(),"класс", "classroom"));
                realm.insert(new Word(Word.increment(),"школа", "school"));
                realm.insert(new Word(Word.increment(),"детский сад", "day care center"));
                realm.insert(new Word(Word.increment(),"детский сад", "kindergarten"));
                realm.insert(new Word(Word.increment(),"начальная школа", "elementary school"));
                realm.insert(new Word(Word.increment(),"средняя школа", "middle school"));
                realm.insert(new Word(Word.increment(),"старшая школа", "high school"));
                realm.insert(new Word(Word.increment(),"университет", "university"));
                realm.insert(new Word(Word.increment(),"улица", "street"));
                realm.insert(new Word(Word.increment(),"мост", "bridge"));
                realm.insert(new Word(Word.increment(),"фабрика", "factory"));
                realm.insert(new Word(Word.increment(),"под землей", "underground"));
                realm.insert(new Word(Word.increment(),"склад", "warehouse"));
                realm.insert(new Word(Word.increment(),"бейсбольный стадион", "baseball stadium"));
                realm.insert(new Word(Word.increment(),"тренажерный зал", "gym"));
                realm.insert(new Word(Word.increment(),"буддистский храм", "buddhist temple"));
                realm.insert(new Word(Word.increment(),"кафедральный собор", "cathedral"));
                realm.insert(new Word(Word.increment(),"церковь", "church"));
                realm.insert(new Word(Word.increment(),"тюрьма", "prison"));
                realm.insert(new Word(Word.increment(),"экономика", "economy"));
                realm.insert(new Word(Word.increment(),"потребление", "consumption"));
                realm.insert(new Word(Word.increment(),"сбережения", "savings"));
                realm.insert(new Word(Word.increment(),"бюджет", "budget"));
                realm.insert(new Word(Word.increment(),"капитал", "capital"));
                realm.insert(new Word(Word.increment(),"услуга", "service"));
                realm.insert(new Word(Word.increment(),"кредит", "loan"));
                realm.insert(new Word(Word.increment(),"финансы", "finance"));
                realm.insert(new Word(Word.increment(),"торговля", "trade"));
                realm.insert(new Word(Word.increment(),"импорт", "import"));
                realm.insert(new Word(Word.increment(),"экспорт", "export"));
                realm.insert(new Word(Word.increment(),"банк", "bank"));
                realm.insert(new Word(Word.increment(),"валюта", "currency"));
                realm.insert(new Word(Word.increment(),"обменный курс", "exchange rate"));
                realm.insert(new Word(Word.increment(),"цена", "price"));
                realm.insert(new Word(Word.increment(),"компания", "company"));
                realm.insert(new Word(Word.increment(),"потребитель", "consumer"));
                realm.insert(new Word(Word.increment(),"производитель", "producer"));
                realm.insert(new Word(Word.increment(),"спрос", "demand"));
                realm.insert(new Word(Word.increment(),"поставка", "supply"));
                realm.insert(new Word(Word.increment(),"доход", "income"));
                realm.insert(new Word(Word.increment(),"безработица", "unemployment"));
                realm.insert(new Word(Word.increment(),"экономический рост", "economic growth"));
                realm.insert(new Word(Word.increment(),"наем", "employment"));
                realm.insert(new Word(Word.increment(),"увольнение", "dismissal"));
                realm.insert(new Word(Word.increment(),"доля", "interest"));
                realm.insert(new Word(Word.increment(),"сберегательная книжка", "passbook"));
                realm.insert(new Word(Word.increment(),"депозит", "deposit"));
                realm.insert(new Word(Word.increment(),"снятие", "withdrawal"));
                realm.insert(new Word(Word.increment(),"перевод", "transfer"));
                realm.insert(new Word(Word.increment(),"дебетовая карточка", "debit card"));
                realm.insert(new Word(Word.increment(),"кредитная карта", "credit card"));
                realm.insert(new Word(Word.increment(),"квитанция", "receipt"));
                realm.insert(new Word(Word.increment(),"компания", "company"));
                realm.insert(new Word(Word.increment(),"босс", "boss"));
                realm.insert(new Word(Word.increment(),"секретарь", "secretary"));
                realm.insert(new Word(Word.increment(),"собеседование", "interview"));
                realm.insert(new Word(Word.increment(),"коллега", "colleague"));
                realm.insert(new Word(Word.increment(),"повышение", "promotion"));
                realm.insert(new Word(Word.increment(),"отставка", "resignation"));
                realm.insert(new Word(Word.increment(),"свидетельство", "certificate"));
                realm.insert(new Word(Word.increment(),"искать работу", "to look for a job"));
                realm.insert(new Word(Word.increment(),"нанимать", "to employ"));
                realm.insert(new Word(Word.increment(),"офис", "office"));
                realm.insert(new Word(Word.increment(),"карьера", "career"));
                realm.insert(new Word(Word.increment(),"командировка", "business trip"));
                realm.insert(new Word(Word.increment(),"встреча", "meeting"));
                realm.insert(new Word(Word.increment(),"отпуск", "leave"));
                realm.insert(new Word(Word.increment(),"резюме", "résumé"));
                realm.insert(new Word(Word.increment(),"набор персонала", "recruitment"));
                realm.insert(new Word(Word.increment(),"уходить с работы", "to get off work"));
                realm.insert(new Word(Word.increment(),"отсутствовать", "to be absent"));
                realm.insert(new Word(Word.increment(),"вести переговоры", "to negotiate"));
                realm.insert(new Word(Word.increment(),"уволить", "to fire"));
                realm.insert(new Word(Word.increment(),"выходить на пенсию", "to retire"));
                realm.insert(new Word(Word.increment(),"работа", "work"));
                realm.insert(new Word(Word.increment(),"рабочие часы", "office hours"));
                realm.insert(new Word(Word.increment(),"зарплата", "salary"));
                realm.insert(new Word(Word.increment(),"бонус", "bonus"));
                realm.insert(new Word(Word.increment(),"рабочий стол", "desk"));
                realm.insert(new Word(Word.increment(),"ксерокс", "photocopier"));
                realm.insert(new Word(Word.increment(),"ноутбук", "laptop"));
                realm.insert(new Word(Word.increment(),"факс", "fax"));
                realm.insert(new Word(Word.increment(),"калькулятор", "calculator"));
                realm.insert(new Word(Word.increment(),"календарь", "calendar"));
                realm.insert(new Word(Word.increment(),"телефон", "phone"));
                realm.insert(new Word(Word.increment(),"блокнот", "notebook"));
                realm.insert(new Word(Word.increment(),"степлер", "stapler"));
                realm.insert(new Word(Word.increment(),"мышь", "mouse"));
                realm.insert(new Word(Word.increment(),"ручка", "pen"));
                realm.insert(new Word(Word.increment(),"стикеры", "post-it"));
                realm.insert(new Word(Word.increment(),"скрепка", "clip"));
                realm.insert(new Word(Word.increment(),"принтер", "printer"));
                realm.insert(new Word(Word.increment(),"бумага", "paper"));
                realm.insert(new Word(Word.increment(),"ножницы", "scissors"));
                realm.insert(new Word(Word.increment(),"карандаш", "pencil"));
                realm.insert(new Word(Word.increment(),"ластик", "eraser"));
                realm.insert(new Word(Word.increment(),"маркер", "highlighter"));
                realm.insert(new Word(Word.increment(),"стул", "chair"));
                realm.insert(new Word(Word.increment(),"скотч", "tape"));
                realm.insert(new Word(Word.increment(),"клей", "glue"));
                realm.insert(new Word(Word.increment(),"математика", "mathematics"));
                realm.insert(new Word(Word.increment(),"наука", "science"));
                realm.insert(new Word(Word.increment(),"физкультура", "physical education"));
                realm.insert(new Word(Word.increment(),"музыка", "music"));
                realm.insert(new Word(Word.increment(),"искусство", "art"));
                realm.insert(new Word(Word.increment(),"английский язык", "English"));
                realm.insert(new Word(Word.increment(),"грамматика", "grammar"));
                realm.insert(new Word(Word.increment(),"плата за обучение", "tuition fee"));
                realm.insert(new Word(Word.increment(),"табель", "report card"));
                realm.insert(new Word(Word.increment(),"стипендия", "scholarship"));
                realm.insert(new Word(Word.increment(),"общежитие", "dormitory"));
                realm.insert(new Word(Word.increment(),"учитель", "teacher"));
                realm.insert(new Word(Word.increment(),"профессор", "professor"));
                realm.insert(new Word(Word.increment(),"вопрос с вариантами ответов", "multiple-choice question"));
                realm.insert(new Word(Word.increment(),"сочинение", "essay"));
                realm.insert(new Word(Word.increment(),"викторина", "quiz"));
                realm.insert(new Word(Word.increment(),"промежуточный экзамен", "mid-term exam"));
                realm.insert(new Word(Word.increment(),"итоговый экзамен", "final exam"));
                realm.insert(new Word(Word.increment(),"специальность", "major"));
                realm.insert(new Word(Word.increment(),"первокурсник", "freshman"));
                realm.insert(new Word(Word.increment(),"второкурсник", "sophomore"));
                realm.insert(new Word(Word.increment(),"выпускник", "graduate"));
                realm.insert(new Word(Word.increment(),"лекция", "lecture"));
                realm.insert(new Word(Word.increment(),"обзор", "review"));
                realm.insert(new Word(Word.increment(),"домашнее задание", "homework"));
                realm.insert(new Word(Word.increment(),"отчет", "report"));
                realm.insert(new Word(Word.increment(),"диплом", "diploma"));
                realm.insert(new Word(Word.increment(),"выпускной", "graduation"));
                realm.insert(new Word(Word.increment(),"студенческий билет", "student ID"));
                realm.insert(new Word(Word.increment(),"класс", "classroom"));
                realm.insert(new Word(Word.increment(),"школа", "school"));
                realm.insert(new Word(Word.increment(),"школьная столовая", "school cafeteria"));
                realm.insert(new Word(Word.increment(),"лаборатория", "laboratory"));
                realm.insert(new Word(Word.increment(),"музыкальный класс", "music classroom"));
                realm.insert(new Word(Word.increment(),"тренажерный зал", "gym"));
                realm.insert(new Word(Word.increment(),"библиотека", "library"));
                realm.insert(new Word(Word.increment(),"комната отдыха", "restroom"));
                realm.insert(new Word(Word.increment(),"бассейн", "swimming pool"));
                realm.insert(new Word(Word.increment(),"прихожая", "hallway"));
                realm.insert(new Word(Word.increment(),"школьная форма", "school uniform"));
                realm.insert(new Word(Word.increment(),"спортивная одежда", "gym clothes"));
                realm.insert(new Word(Word.increment(),"галстук", "tie"));
                realm.insert(new Word(Word.increment(),"рубашка", "shirt"));
                realm.insert(new Word(Word.increment(),"лучший ученик", "top student"));
                realm.insert(new Word(Word.increment(),"комната для преподавателей", "faculty lounge"));
                realm.insert(new Word(Word.increment(),"шкафчик", "locker"));
                realm.insert(new Word(Word.increment(),"школьные ворота", "school gate"));
                realm.insert(new Word(Word.increment(),"школьная еда", "school meal"));
                realm.insert(new Word(Word.increment(),"учебник", "textbook"));
                realm.insert(new Word(Word.increment(),"кабинет медсестры", "nurse's office"));
                realm.insert(new Word(Word.increment(),"звонок", "bell"));
                realm.insert(new Word(Word.increment(),"доска", "blackboard"));
                realm.insert(new Word(Word.increment(),"стул", "chair"));
                realm.insert(new Word(Word.increment(),"перерыв", "break time"));
                realm.insert(new Word(Word.increment(),"обед", "lunch time"));
                realm.insert(new Word(Word.increment(),"учебный час", "school hour"));
                realm.insert(new Word(Word.increment(),"карандаш", "pencil"));
                realm.insert(new Word(Word.increment(),"ручка", "pen"));
                realm.insert(new Word(Word.increment(),"рекомендательное письмо", "letter of recommendation"));
                realm.insert(new Word(Word.increment(),"ластик", "eraser"));
                realm.insert(new Word(Word.increment(),"тетрадь", "notebook"));
                realm.insert(new Word(Word.increment(),"рюкзак", "backpack"));
                realm.insert(new Word(Word.increment(),"ножницы", "scissors"));
                realm.insert(new Word(Word.increment(),"клей", "glue"));
                realm.insert(new Word(Word.increment(),"краски", "paint"));
                realm.insert(new Word(Word.increment(),"летние каникулы", "summer vacation"));
                realm.insert(new Word(Word.increment(),"зимние каникулы", "winter vacation"));
                realm.insert(new Word(Word.increment(),"актовый зал", "auditorium"));
                realm.insert(new Word(Word.increment(),"ластик для доски", "blackboard eraser"));
                realm.insert(new Word(Word.increment(),"маркер для доски", "board marker"));
                realm.insert(new Word(Word.increment(),"презентация", "presentation"));
                realm.insert(new Word(Word.increment(),"групповой проект", "group project"));
                realm.insert(new Word(Word.increment(),"работа волонтером", "volunteer work"));
                realm.insert(new Word(Word.increment(),"ноутбук", "laptop"));
                realm.insert(new Word(Word.increment(),"подиум", "podium"));
                realm.insert(new Word(Word.increment(),"средняя школа", "middle school"));
                realm.insert(new Word(Word.increment(),"университет", "universtiy"));
                realm.insert(new Word(Word.increment(),"высшая школа", "graduate school"));
                realm.insert(new Word(Word.increment(),"внеклассные занятия", "extra-curricular activities"));
                realm.insert(new Word(Word.increment(),"дружба", "friendship"));
                realm.insert(new Word(Word.increment(),"друг", "friend"));
                realm.insert(new Word(Word.increment(),"предприниматель", "businessman"));
                realm.insert(new Word(Word.increment(),"секретарь", "secretary"));
                realm.insert(new Word(Word.increment(),"программист", "programmer"));
                realm.insert(new Word(Word.increment(),"дизайнер", "designer"));
                realm.insert(new Word(Word.increment(),"парикмахер", "hairdresser"));
                realm.insert(new Word(Word.increment(),"пекарь", "baker"));
                realm.insert(new Word(Word.increment(),"повар", "chef"));
                realm.insert(new Word(Word.increment(),"телохранитель", "bodyguard"));
                realm.insert(new Word(Word.increment(),"охранник", "guard"));
                realm.insert(new Word(Word.increment(),"медсестра", "nurse"));
                realm.insert(new Word(Word.increment(),"няня", "babysitter"));
                realm.insert(new Word(Word.increment(),"дантист", "dentist"));
                realm.insert(new Word(Word.increment(),"врач", "doctor"));
                realm.insert(new Word(Word.increment(),"ветеринар", "vet"));
                realm.insert(new Word(Word.increment(),"фармацевт", "pharmacist"));
                realm.insert(new Word(Word.increment(),"архитектор", "architect"));
                realm.insert(new Word(Word.increment(),"плотник", "carpenter"));
                realm.insert(new Word(Word.increment(),"садовник", "gardener"));
                realm.insert(new Word(Word.increment(),"инструктор", "trainer"));
                realm.insert(new Word(Word.increment(),"мастер маникюра", "manicurist"));
                realm.insert(new Word(Word.increment(),"пилот", "pilot"));
                realm.insert(new Word(Word.increment(),"туристический гид", "tour guide"));
                realm.insert(new Word(Word.increment(),"официант", "waiter"));
                realm.insert(new Word(Word.increment(),"официантка", "waitress"));
                realm.insert(new Word(Word.increment(),"бортпроводник", "flight attendant"));
                realm.insert(new Word(Word.increment(),"поэт", "poet"));
                realm.insert(new Word(Word.increment(),"художник", "painter"));
                realm.insert(new Word(Word.increment(),"музыкант", "musician"));
                realm.insert(new Word(Word.increment(),"автор", "author"));
                realm.insert(new Word(Word.increment(),"политик", "politician"));
                realm.insert(new Word(Word.increment(),"президент", "president"));
                realm.insert(new Word(Word.increment(),"журналист", "journalist"));
                realm.insert(new Word(Word.increment(),"фотограф", "photographer"));
                realm.insert(new Word(Word.increment(),"модель", "model"));
                realm.insert(new Word(Word.increment(),"актер", "actor"));
                realm.insert(new Word(Word.increment(),"актриса", "actress"));
                realm.insert(new Word(Word.increment(),"комедиант", "comedian"));
                realm.insert(new Word(Word.increment(),"режиссер", "movie director"));
                realm.insert(new Word(Word.increment(),"автор песен", "songwriter"));
                realm.insert(new Word(Word.increment(),"диктор", "newscaster"));
                realm.insert(new Word(Word.increment(),"певец", "singer"));
                realm.insert(new Word(Word.increment(),"полицейский", "policeman"));
                realm.insert(new Word(Word.increment(),"футболист", "soccer player"));
                realm.insert(new Word(Word.increment(),"спортсмен", "athlete"));
                realm.insert(new Word(Word.increment(),"директор", "principal"));
                realm.insert(new Word(Word.increment(),"учитель", "teacher"));
                realm.insert(new Word(Word.increment(),"профессор", "professor"));
                realm.insert(new Word(Word.increment(),"ученый", "scientist"));
                realm.insert(new Word(Word.increment(),"космонавт", "astronaut"));
                realm.insert(new Word(Word.increment(),"пожарник", "fireman"));
                realm.insert(new Word(Word.increment(),"солдат", "soldier"));
                realm.insert(new Word(Word.increment(),"рыбак", "fisherman"));
                realm.insert(new Word(Word.increment(),"фермер", "farmer"));
                realm.insert(new Word(Word.increment(),"шахтер", "miner"));
                realm.insert(new Word(Word.increment(),"переводчик", "interpreter"));
                realm.insert(new Word(Word.increment(),"переводчик", "translator"));
                realm.insert(new Word(Word.increment(),"почтальон", "mailman"));
                realm.insert(new Word(Word.increment(),"наводнение", "flood"));
                realm.insert(new Word(Word.increment(),"засуха", "drought"));
                realm.insert(new Word(Word.increment(),"землетрясение", "earthquake"));
                realm.insert(new Word(Word.increment(),"извержение вулкана", "volcanic eruption"));
                realm.insert(new Word(Word.increment(),"пожар", "fire"));
                realm.insert(new Word(Word.increment(),"взрыв", "explosion"));
                realm.insert(new Word(Word.increment(),"цунами", "tsunami"));
                realm.insert(new Word(Word.increment(),"ливень", "heavy rain"));
                realm.insert(new Word(Word.increment(),"снегопад", "heavy snow"));
                realm.insert(new Word(Word.increment(),"град", "hail"));
                realm.insert(new Word(Word.increment(),"разлив нефти", "oil spill"));
                realm.insert(new Word(Word.increment(),"дорожная авария", "car accident"));
                realm.insert(new Word(Word.increment(),"эпидемия", "epidemic"));
                realm.insert(new Word(Word.increment(),"терроризм", "terrorism"));
                realm.insert(new Word(Word.increment(),"карманник", "pickpocket"));
                realm.insert(new Word(Word.increment(),"взрыв газа", "gas explosion"));
                realm.insert(new Word(Word.increment(),"загрязнение окружающей среды", "environmental pollution"));
                realm.insert(new Word(Word.increment(),"оползень", "landslide"));
                realm.insert(new Word(Word.increment(),"война", "war"));
                realm.insert(new Word(Word.increment(),"погода", "weather"));
                realm.insert(new Word(Word.increment(),"солнце", "sun"));
                realm.insert(new Word(Word.increment(),"облако", "cloud"));
                realm.insert(new Word(Word.increment(),"дождь", "rain"));
                realm.insert(new Word(Word.increment(),"снег", "snow"));
                realm.insert(new Word(Word.increment(),"заморозить", "to freeze"));
                realm.insert(new Word(Word.increment(),"туман", "fog"));
                realm.insert(new Word(Word.increment(),"ветер", "wind"));
                realm.insert(new Word(Word.increment(),"тайфун", "typhoon"));
                realm.insert(new Word(Word.increment(),"гром", "thunder"));
                realm.insert(new Word(Word.increment(),"молния", "lightning"));
                realm.insert(new Word(Word.increment(),"буря", "storm"));
                realm.insert(new Word(Word.increment(),"торнадо", "tornado"));
                realm.insert(new Word(Word.increment(),"ураган", "hurricane"));
                realm.insert(new Word(Word.increment(),"метель", "snowstorm"));
                realm.insert(new Word(Word.increment(),"жаркий", "hot"));
                realm.insert(new Word(Word.increment(),"холодный", "cold"));
                realm.insert(new Word(Word.increment(),"теплый", "warm"));
                realm.insert(new Word(Word.increment(),"чистый", "clear"));
                realm.insert(new Word(Word.increment(),"облачный", "cloudy"));
                realm.insert(new Word(Word.increment(),"прогноз погоды", "weather forecast"));
                realm.insert(new Word(Word.increment(),"температура воздуха", "air temperature"));
                realm.insert(new Word(Word.increment(),"температура", "temperature"));
                realm.insert(new Word(Word.increment(),"климат", "climate"));
                realm.insert(new Word(Word.increment(),"глобальное потепление", "global warming"));
                realm.insert(new Word(Word.increment(),"земельные участки", "land"));
                realm.insert(new Word(Word.increment(),"море", "sea"));
                realm.insert(new Word(Word.increment(),"континент", "continent"));
                realm.insert(new Word(Word.increment(),"океан", "ocean"));
                realm.insert(new Word(Word.increment(),"южный полюс", "South Pole"));
                realm.insert(new Word(Word.increment(),"остров", "island"));
                realm.insert(new Word(Word.increment(),"холм", "hill"));
                realm.insert(new Word(Word.increment(),"гора", "mountain"));
                realm.insert(new Word(Word.increment(),"вулкан", "volcano"));
                realm.insert(new Word(Word.increment(),"песок", "sand"));
                realm.insert(new Word(Word.increment(),"пустыня", "desert"));
                realm.insert(new Word(Word.increment(),"скала", "cliff"));
                realm.insert(new Word(Word.increment(),"долина", "valley"));
                realm.insert(new Word(Word.increment(),"пляж", "beach"));
                realm.insert(new Word(Word.increment(),"плотина", "dam"));
                realm.insert(new Word(Word.increment(),"пруд", "pond"));
                realm.insert(new Word(Word.increment(),"водопад", "waterfall"));
                realm.insert(new Word(Word.increment(),"река", "river"));
                realm.insert(new Word(Word.increment(),"озеро", "lake"));
                realm.insert(new Word(Word.increment(),"болото", "swamp"));
                realm.insert(new Word(Word.increment(),"луг", "meadow"));
                realm.insert(new Word(Word.increment(),"лес", "forest"));
                realm.insert(new Word(Word.increment(),"джунгли", "jungle"));
                realm.insert(new Word(Word.increment(),"пещера", "cave"));
                realm.insert(new Word(Word.increment(),"айсберг", "iceberg"));
                realm.insert(new Word(Word.increment(),"ледник", "glacier"));
                realm.insert(new Word(Word.increment(),"загрязнение", "pollution"));
                realm.insert(new Word(Word.increment(),"карта", "map"));
                realm.insert(new Word(Word.increment(),"урбанизация", "urbanization"));
                realm.insert(new Word(Word.increment(),"торговля", "trade"));
                realm.insert(new Word(Word.increment(),"компас", "compass"));
                realm.insert(new Word(Word.increment(),"восток", "east"));
                realm.insert(new Word(Word.increment(),"запад", "west"));
                realm.insert(new Word(Word.increment(),"север", "north"));
                realm.insert(new Word(Word.increment(),"столица", "capital"));
                realm.insert(new Word(Word.increment(),"азия", "Asia"));
                realm.insert(new Word(Word.increment(),"африка", "Africa"));
                realm.insert(new Word(Word.increment(),"океания", "Oceania"));
                realm.insert(new Word(Word.increment(),"северная америка", "North America"));
                realm.insert(new Word(Word.increment(),"южная америка", "South America"));
                realm.insert(new Word(Word.increment(),"евразия", "Eurasia"));
                realm.insert(new Word(Word.increment(),"средиземное море", "Mediterranean sea"));
                realm.insert(new Word(Word.increment(),"средний восток", "Middle East"));
                realm.insert(new Word(Word.increment(),"космос", "space"));
                realm.insert(new Word(Word.increment(),"космический корабль", "spacecraft"));
                realm.insert(new Word(Word.increment(),"космонавт", "astronaut"));
                realm.insert(new Word(Word.increment(),"спутник", "satellite"));
                realm.insert(new Word(Word.increment(),"галактика", "galaxy"));
                realm.insert(new Word(Word.increment(),"звезда", "star"));
                realm.insert(new Word(Word.increment(),"комета", "comet"));
                realm.insert(new Word(Word.increment(),"астероид", "asteroid"));
                realm.insert(new Word(Word.increment(),"черная дыра", "black hole"));
                realm.insert(new Word(Word.increment(),"большой взрыв", "Big Bang"));
                realm.insert(new Word(Word.increment(),"сила тяжести", "gravity"));
                realm.insert(new Word(Word.increment(),"нулевая гравитация", "zero gravity"));
                realm.insert(new Word(Word.increment(),"луна", "moon"));
                realm.insert(new Word(Word.increment(),"солнечная система", "Solar System"));
                realm.insert(new Word(Word.increment(),"солнце", "Sun"));
                realm.insert(new Word(Word.increment(),"марс", "Mars"));
                realm.insert(new Word(Word.increment(),"созвездие", "constellation"));
                realm.insert(new Word(Word.increment(),"материя", "matter"));
                realm.insert(new Word(Word.increment(),"воздух", "air"));
                realm.insert(new Word(Word.increment(),"металл", "metal"));
                realm.insert(new Word(Word.increment(),"железо", "iron"));
                realm.insert(new Word(Word.increment(),"гелий", "helium"));
                realm.insert(new Word(Word.increment(),"углерод", "carbon"));
                realm.insert(new Word(Word.increment(),"азот", "nitrogen"));
                realm.insert(new Word(Word.increment(),"кислород", "oxygen"));
                realm.insert(new Word(Word.increment(),"алюминий", "aluminum"));
                realm.insert(new Word(Word.increment(),"углекислый газ", "carbon dioxide"));
                realm.insert(new Word(Word.increment(),"золото", "gold"));
                realm.insert(new Word(Word.increment(),"серебро", "silver"));
                realm.insert(new Word(Word.increment(),"медь", "copper"));
                realm.insert(new Word(Word.increment(),"лазерный", "laser"));
                realm.insert(new Word(Word.increment(),"видимый свет", "visible light"));
                realm.insert(new Word(Word.increment(),"ультрафиолетовые лучи", "UV rays"));
                realm.insert(new Word(Word.increment(),"инфракрасный луч", "infrared ray"));
                realm.insert(new Word(Word.increment(),"излучение", "radiation"));
                realm.insert(new Word(Word.increment(),"ядро", "nucleus"));
                realm.insert(new Word(Word.increment(),"дым", "smoke"));
                realm.insert(new Word(Word.increment(),"пар", "vapor"));
                realm.insert(new Word(Word.increment(),"жидкость", "liquid"));
                realm.insert(new Word(Word.increment(),"твердое тело", "solid"));
                realm.insert(new Word(Word.increment(),"газ", "gas"));
                realm.insert(new Word(Word.increment(),"масло", "oil"));
                realm.insert(new Word(Word.increment(),"каменный уголь", "coal"));
                realm.insert(new Word(Word.increment(),"озон", "ozone"));
                realm.insert(new Word(Word.increment(),"лед", "ice"));
                realm.insert(new Word(Word.increment(),"электричество", "electricity"));
                realm.insert(new Word(Word.increment(),"пластик", "plastic"));
                realm.insert(new Word(Word.increment(),"энергия", "energy"));
                realm.insert(new Word(Word.increment(),"пенополистирол", "styrofoam"));
                realm.insert(new Word(Word.increment(),"вирус", "virus"));
                realm.insert(new Word(Word.increment(),"бактерия", "bacteria"));
                realm.insert(new Word(Word.increment(),"ген", "gene"));
                realm.insert(new Word(Word.increment(),"терапия", "Internal Medicine  "));
                realm.insert(new Word(Word.increment(),"стоматология", "Dentistry"));
                realm.insert(new Word(Word.increment(),"дерматология", "Dermatology  "));
                realm.insert(new Word(Word.increment(),"акушерство и гинекология", "Obstetrics and Gynecology  "));
                realm.insert(new Word(Word.increment(),"пластическая хирургия", "Plastic Surgery  "));
                realm.insert(new Word(Word.increment(),"офтальмология", "Ophthalmology"));
            }
        };
    }
    //endregion
}
